-- useful only in pgsql
-- SELECT last_checkout - last_checkin
-- FROM memberships;
--
-- mysql
-- SELECT TIMESTAMPDIFF(MINUTE, last_checkin, last_checkout)
-- FROM memberships;
--
-- pgsql
-- SELECT membership_end - membership_start
-- FROM memberships;
--
-- mysql
-- SELECT DATEDIFF(NOW(), membership_start)
-- FROM memberships;